### ISSUE TITLE
CCM Test Stand Configuration problem

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/ut-hw-doc#4]
Hey Rohan,

The latest update you made has some problems:
1. If it's a new topic, it's better to create a new folder
2. Inconsistent indentation
3. Missing pictures, such as `ccm_id1.png`.

**Comment by yipengsun** [comment]
In general, please visit the actual webpage after Travis finishes building and see if the result looks OK.

**Comment by yipengsun** [comment]
It is preferable if you build the site and test it locally. But if that's a hassle (which I don't think so), please do check the actual webpage instead.

**Comment by yipengsun** [comment]
@keplerman417 Can you take a look at this if time permits?

**Comment by Svende** [comment]
Hi Rohan, 
I am adding here the part which I asked you to do on slack on the 13th of March, please consider this also as a part of your project:
'Raymond have had big problems with the CCM QA yesterday. I looked into it with Phoebe today and it turned out that the setup wasn't correctly for 1.2A's. That was very confusing for us since you and Thomas QAed 1.2A's earlier this week. I went to check out the documentation you wrote for the setup and found that this is not finished. There are at least missing pictures, also the last sentence is not final, can you please fix that remotely today? afaik the problem was that following https://umd-lhcb.github.io/ut-hw-doc/lvr/lvr_config/lvr_config/ with 'Configuration of LVR'. The LVR was not configured for the corresponding CCMs through the potentiometers P3 and P4, they were still setup for 2.5V.  Could you please add this part also to the documentation and remember to change it in the setup for the different CCMs'.

Also as mentioned by Manuel in his email with the projects, please add some additional information to the LVR QA page. We talked about that a while ago, this is that people understand better what the tests which are done during the QA are for. Please take a look at the DCB QA page to get an idea what we are thinking of, Derek did a great job on explaining the basic functionalities we are testing for there. Please let us know if you have any questions or anything is unclear. Just imagine me sitting next to you during the LVR QA asking questions like 'Why? What is that for? What do we want to test?' ;) Hope that helps!

**Comment by yipengsun** [comment]
This is a reminder to us that we still need to fix Rohan's _Test Stand Configuration_ documentation.

**Comment by Svende** [comment]
Thanks, I guess this would be for @CoffeeIntoScience as I don't know the details, but I guess that' not so important for now, only if we need to test CCMs later

**Comment by yipengsun** [comment]
This page now becomes more weird: https://umd-lhcb.github.io/ut-hw-doc/lvr/ccm_test_stand_config/ccm_test_stand_config

Do we still need this page, after all? I'm inclined to just disable (not delete) this page and call it a day.

**Comment by Svende** [comment]
Yes we do need this page, I think the latest changes were made by @manuelfs

**Comment by yipengsun** [comment]
@manuelfs Also, you didn't upload the pictures. Can you upload them?

**Comment by manuelfs** [comment]
I just commented out the missing figure statements because they were giving warnings.

I looked for them a bit in the GitHub history, and asked @CoffeeIntoScience to look for them, but neither of us could find them. They may need to be taken again.

**Comment by yipengsun** [comment]
OK I see. I think the reason I opened this issue is that I could not find any picture that Rohan was using, and my original intention was ask Rohan to minimally submit these figures (more cleanups would be better, but with figures at least we could consider the documentation _complete_).

The conclusion is: There's no real progress on making this particular page work. If we don't plan to use it in the future, can we disable the generation of this page (comment out the entry pointing to this page in the YAML file should be sufficient)?

**Comment by yipengsun** [comment]
Or, we could take the pictures again. But we should consider if we do need this page, after all (since nobody seems to be complaining about this page being incomplete).

**Comment by yipengsun** [comment]
Any new suggestions on this? If not, I'll disable the generation of this page on this Friday.

**Comment by yipengsun** [comment]
No, I re-read Svend's comment, and realized that we probably do need this page. So we need to re-take pictures.

**Comment by yipengsun** [comment]
I see that all missing pictures are retaken. Problem solved.
